# Generated by Django 4.1.7 on 2023-03-08 17:48

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_community_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Create at ')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='Modify at ')),
                ('active', models.BooleanField(default=True, verbose_name='Active? ')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to='images', variations={'thumb': (300, 300)}, verbose_name='Image')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('content', models.CharField(max_length=200, verbose_name='Content')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
